
package View;

import Presenters.PresentadorAltaEspecie;


public class ViewAltaEspecie extends javax.swing.JFrame {
    PresentadorAltaEspecie presentadorAlta;

    public ViewAltaEspecie() {
        presentadorAlta = new PresentadorAltaEspecie();
        presentadorAlta.setVistaEspecie(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnConfirmarEspecie = new javax.swing.JButton();
        cmbDieta = new javax.swing.JComboBox();
        especieAnimal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorCarnivoro = new javax.swing.JTextField();
        Jlabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEspecie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnConfirmarEspecie.setText("Confirmar");
        BtnConfirmarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarEspecieActionPerformed(evt);
            }
        });

        cmbDieta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CARNIVORO", "HERBIVORO" }));
        cmbDieta.setName(""); // NOI18N
        cmbDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDietaActionPerformed(evt);
            }
        });

        especieAnimal.setText("Nombre");

        jLabel4.setText("Porcentaje Carnivoro:");

        txtValorCarnivoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCarnivoroActionPerformed(evt);
            }
        });
        txtValorCarnivoro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtValorCarnivoroPropertyChange(evt);
            }
        });

        Jlabel.setText("Dieta");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Alta Especie");

        txtNombreEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEspecieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especieAnimal)
                            .addComponent(jLabel1)
                            .addComponent(Jlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorCarnivoro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(BtnConfirmarEspecie)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especieAnimal)
                    .addComponent(txtNombreEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorCarnivoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(BtnConfirmarEspecie)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarEspecieActionPerformed
        
        presentadorAlta.createEspecie(txtNombreEspecie.getText(),txtValorCarnivoro.getText(),cmbDieta.getSelectedItem().toString());
        
    }//GEN-LAST:event_BtnConfirmarEspecieActionPerformed

    private void txtValorCarnivoroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtValorCarnivoroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCarnivoroPropertyChange

    private void txtValorCarnivoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCarnivoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCarnivoroActionPerformed

    private void txtNombreEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEspecieActionPerformed

    private void cmbDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDietaActionPerformed
       String dieta = cmbDieta.getSelectedItem().toString();
        if(dieta.equalsIgnoreCase("Herbivoro")){
                        this.txtValorCarnivoro.setEnabled(false);
                        this.txtValorCarnivoro.setText("0");
        }
        else{
             this.txtValorCarnivoro.setEnabled(true);
            this.txtValorCarnivoro.setText("");
        }
    }//GEN-LAST:event_cmbDietaActionPerformed

   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmarEspecie;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JComboBox cmbDieta;
    private javax.swing.JLabel especieAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNombreEspecie;
    private javax.swing.JTextField txtValorCarnivoro;
    // End of variables declaration//GEN-END:variables
}
